### ISSUE TITLE
Running embed Mongo manually fails

### ISSUE THREAD

**Issue by wortner** [joelittlejohn/embedmongo-maven-plugin#42]
Hi, I'd like to run this plugin manually embedmongo:start (not binding it to maven lifecycle phases), but I'm getting java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils.  <dependencies> inside plugin definition didn't help. When running for integration test I don't have this problem. 

```
[INFO] --- embedmongo-maven-plugin:0.1.12:start (default-cli) @ technicalblog ---
Extract C:\Users\.embedmongo\win32\mongodb-win32-x86_64-2008plus-2.2.1.zip START
Extract C:\Users\.embedmongo\win32\mongodb-win32-x86_64-2008plus-2.2.1.zip DONE
[mongod output]note: noprealloc may hurt performance in many applications
[mongod output] Mon Jun 15 10:03:47 [initandlisten] MongoDB starting : pid=11436 port=27017 dbpath=C:\Users\-\AppData\Local\Temp\embedmongo-db-a9bae38c-0479-404a-9a91-f9ed63d03fa4 64-bit host=jj
[mongod output] Mon Jun 15 10:03:47 [initandlisten] db version v2.2.1, pdfile version 4.5
[mongod output] Mon Jun 15 10:03:47 [initandlisten] git version: d6764bf8dfe0685521b8bc7b98fd1fab8cfeb5ae
[mongod output] Mon Jun 15 10:03:47 [initandlisten] build info: windows sys.getwindowsversion(major=6, minor=1, build=7601, platform=2, service_pack='Service Pack 1') BOOST_LIB_VERSION=1_49
[mongod output] Mon Jun 15 10:03:47 [initandlisten] options: { dbpath: "C:\Users\AppData\Local\Temp\embedmongo-db-a9bae38c-0479-404a-9a91-f9ed63d03fa4", noauth: true, nohttpinterface: true, nojournal: true, nopreal
loc: true, port: 27017, smallfiles: true }
[mongod output] Mon Jun 15 10:03:47 [initandlisten] Unable to check for journal files due to: boost::filesystem::basic_directory_iterator constructor: SystÚm nem¨×e nalÚzt uvedenou cestu: "C:\Users\AppData\Local\Te
mp\embedmongo-db-a9bae38c-0479-404a-9a91-f9ed63d03fa4\journal"
[mongod output] Mon Jun 15 10:03:47 [initandlisten] waiting for connections on port 27017
[mongod output] VI 15, 2015 10:03:47 DOP. MongodExecutable start
INFO: de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@4a980530
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.039 s
[INFO] Finished at: 2015-06-15T10:03:47+02:00
[INFO] Final Memory: 9M/154M
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
        at de.flapdoodle.embed.process.store.ArtifactStore.removeFileSet(ArtifactStore.java:91)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.forceDelete(CachingArtifactStore.java:151)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:94)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:171)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 6 more
Mon Jun 15 10:03:47 [initandlisten] connection accepted from 127.0.0.1:59032 #1 (1 connection now open)
[mongod output] Mon Jun 15 10:03:47 [conn1] terminating, shutdown command received
[mongod output] Mon Jun 15 10:03:47 dbexit: shutdown called
[mongod output] Mon Jun 15 10:03:47 [conn1] shutdown: going to close listening sockets...
[mongod output] Mon Jun 15 10:03:47 [conn1] closing listening socket: 364
[mongod output] Mon Jun 15 10:03:47 [conn1] shutdown: going to flush diaglog...
[mongod output] Mon Jun 15 10:03:47 [conn1] shutdown: going to close sockets...
[mongod output] Mon Jun 15 10:03:47 [conn1] shutdown: waiting for fs preallocator...
[mongod output] Mon Jun 15 10:03:47 [conn1] shutdown: closing all files...
[mongod output] Mon Jun 15 10:03:47 [conn1] closeAllFiles() finished
[mongod output] Mon Jun 15 10:03:47 [conn1] shutdown: removing fs lock...
[mongod output] Mon Jun 15 10:03:47 dbexit: really exiting now
[mongod output]
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
        at de.flapdoodle.embed.mongo.MongodProcess.deleteTempFiles(MongodProcess.java:92)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.cleanupInternal(AbstractMongoProcess.java:116)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:167)
        at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:71)
        at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:88)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by joelittlejohn** [comment]
I think this is actually a problem in the underlying embedmongo flapdoodle API. It's an error thrown on shutdown but I don't think it should stop you achieving what you need.

I assume that you wanted to start mongo and wait? You should be able to achieve this by adding `-Dembedmongo.wait` on the command line when invoking Maven.

**Comment by wortner** [comment]
Ok, I will ignore the error and will use the embedmongo.wait property. I just wrongly presumed the start goal will not stop immediately. Anyway thanks.
